# Generated by Django 4.2.3 on 2023-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hob_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=20, verbose_name='ホブツールNo')),
                ('serial_no', models.CharField(max_length=10, verbose_name='製造番号')),
                ('pg_no', models.CharField(max_length=20, verbose_name='プログラムNo')),
                ('blade_thickness', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='刃厚')),
                ('axial_rake_angle', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='向芯度・すくい角')),
            ],
        ),
    ]
